name: apat/gh-migration
on:
  push:
jobs:
  Build-Stage-checkout:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4.1.0
      with:
        clean: false
    - run: echo "hi"
    - uses: actions/checkout@v4.1.0
      env:
        REPO_NAME: "**org/name**"
      with:
        repository: "${{ env.REPO_NAME }}"
        clean: false
  Security-Stage-security-scan:
    runs-on: ubuntu-latest
    needs:
    - Build-Stage-checkout
    steps:
    - uses: actions/checkout@v4.1.0
      with:
        clean: false
  Deploy-Stage-deploy-e1:
    runs-on: ubuntu-latest
    needs:
    - Build-Stage-checkout
    - Security-Stage-security-scan
    steps:
    - uses: actions/checkout@v4.1.0
      with:
        clean: false
